### ISSUE TITLE
ATU GitHub Activities

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#119]
## GitHub Advanced Security
- [x] Enable CodeQL
- [x] Enable Dependabot
- [x] Enable Secret Scanning
- [x] Designate one GitHub **Team** with `admin` access to the repository
- [x] Designate one or more GitHub **Teams** with `write` access to the repository
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/tts.gsa.gov/issues/91
- [ ] https://github.com/GSA-TTS/tts.gsa.gov/issues/94
- [ ] https://github.com/GSA-TTS/tts.gsa.gov/issues/96
```

**Comment by wesley-dean-gsa** [comment]
Issue #91 (no PR yet) will address the CodeQL configuration.
Issue #96 (PR #97) will address the Dependabot configuration.

**Comment by wesley-dean-gsa** [comment]
Secret Scanning is already enabled.

![Image](https://github.com/user-attachments/assets/5a254703-2213-4cd2-954b-bfb050764033)

**Comment by debjudy** [comment]
No PR needed.  All activities completed. Closing issue.
