### ISSUE TITLE
Display the application cap on the posting

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#445]
As a member of the Talent team, in order to set potential candidate expectations, I want to display the application cap on the posting. 

**Acceptance criteria**
- [ ] Candidates can see the maximum number (cap) applications that will be accepted. 

**Tasks**
- [ ] Display "OR once the XX applicant is met" on the job posting in the "apply now" section  
 ![image](https://github.com/user-attachments/assets/e40d319b-c2f7-49de-8d7c-f5bdab081c7e)
- [ ] Display "OR once the XX applicant is met" on the join page as part of the posting link
![image (1)](https://github.com/user-attachments/assets/884c59a9-bee5-4518-bdd1-ed23b1776ea6)

**Comment by debjudy** [comment]
Approval of updated language as shown in this image in slack https://gsa-tts.slack.com/archives/C07G57Q62E6/p1728388030865129

![Screenshot 2024-10-08 at 12 04 38 PM](https://github.com/user-attachments/assets/c6a31fc4-65a9-467c-a0c1-19a2e4217388)
