### ISSUE TITLE
Add google search console

### ISSUE THREAD

**Issue by debjudy** [GSA-TTS/tts.gsa.gov#462]
As a content strategist, in order to understand inbound traffic, I want to implement Google Search Console. 

**Acceptance criteria**
- [ ]  Site verified for Google Search Console
- [ ] Google search console showing data

**Tasks**
To implement Google Search Console - do one of the following
- [ ]  Upload to https://tts.gsa.gov/ google file found at https://drive.google.com/drive/folders/1KA4LXSeAUYJIk3Yyx69aBrXxm-AXqc61 
**OR**
- [ ] Copy the meta tag below, and paste it into your site's home page. It should go in the <head> section, before the first <body> section.
`<meta name="google-site-verification" content="bpH2FtDPiSmeRUJSQWfFw_-vMHjs3mXAgGbMF3TEwxc" />`
- [ ] Return to https://search.google.com/search-console/welcome for site verification using the URL method.
